---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: helloworld-issuer
spec:
  acme:
    email: mrudul.palvankar@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: helloworld-issuer
    http01: {}
