

apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-telescope-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <EMAIL>
    privateKeySecretRef:
      name: letsencrypt-telescope-dns
    solvers:
    - dns01:
        cnameStrategy: Follow
        digitalocean:
          tokenSecretRef:
            name: telescope-digitalocean-dns
            key: access-token