server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info,metrics,health

spring:
  datasource:
    url: jdbc:mysql://mysql:25060/customers
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
    hibernate:
      ddl-auto: update
